language: python
python:
    - "3.6"
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - conda info -a
    - conda install -c conda-forge --yes mamba
    - conda create --yes -n snakemake-mcl-cluster
    - conda activate snakemake-mcl-cluster
    - mamba install -c conda-forge -c bioconda --yes --file requirements.txt
script:
    - snakemake --printshellcmds --jobs 5 --configfile params.yml -C ceilnb='[100, 1000]' inflation='[1.4, 2]' --directory output/
    - ls -l output/mcl/cluster_summary.tsv
    - ls -l output/mcl/distance_between_clusters.tsv
    - ls -l output/mcl/Pearson_0.6/I_1.4/ceilnb_100/cluster.tsv
