cluster_files = expand('mcl/correlation_{r}/inflation_{inflation}/ceilnb_{ceilnb}/cluster.tsv', 
                r= config['correlation'], inflation= config['inflation'], ceilnb= config['ceilnb'])

rule all:
    input:
        'mcl/similarity_matrix.tsv.gz',
        'mcl/cluster_summary.tsv',
        'mcl/distance_between_clusters.tsv',
        cluster_files,

include: os.path.join(config['workflow_dir'], 'mcl.smk')

